# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1958ffb3c25527698dff11416e7d7857b8673ee89a02739c9ef5cb5243cc155da74f289b35f8f76e80881722c6ae3602ac098c5ee358b8108dead57fd9646ca1

test:
  secret_key_base: 572c61dba197fa4ffe4e5eccea16ac69122f5da8c4c32276bbcce24993ef0ca6e176f25beddc628dbbefe360a38c4e33e958ed74f808bbac6e377da8af901d0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
